# Generated by Django 5.1 on 2024-08-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iziskill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('apprenant', 'Apprenant')], max_length=10, verbose_name='status'),
        ),
    ]
