# Generated by Django 5.1 on 2024-08-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iziskill', '0003_user_bio_user_display_name_user_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.PositiveIntegerField(default=0, verbose_name='Leçons'),
        ),
        migrations.AddField(
            model_name='course',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Prix d'origine"),
        ),
        migrations.AddField(
            model_name='course',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
