# Generated by Django 5.1 on 2024-08-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iziskill', '0006_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='course',
            name='certificat',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='course',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='course',
            name='skill_level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='syllabus',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
    ]
