# Generated by Django 5.1 on 2024-08-29 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iziskill', '0007_remove_course_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Informations supplémentaires'),
        ),
        migrations.AddField(
            model_name='course',
            name='certificat',
            field=models.BooleanField(default=False, verbose_name='Certificat'),
        ),
        migrations.AddField(
            model_name='course',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date du cours'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.TimeField(blank=True, null=True, verbose_name='Durée'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(blank=True, max_length=100, verbose_name='Langue'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True, verbose_name='Prérequis'),
        ),
        migrations.AddField(
            model_name='course',
            name='quiz',
            field=models.BooleanField(default=False, verbose_name='Quiz'),
        ),
        migrations.AddField(
            model_name='course',
            name='skill_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermédiaire'), ('advanced', 'Élevé')], default='basic', max_length=20, verbose_name='Niveau de compétence'),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus',
            field=models.TextField(blank=True, verbose_name='Syllabus'),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iziskill.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paniers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
