# Generated by Django 5.1 on 2024-08-31 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iziskill', '0008_course_additional_info_course_certificat_course_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('details', models.TextField()),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iziskill.course', verbose_name='Cours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
