# Generated by Django 4.2 on 2024-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iziskill', '0009_video_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=0, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
