# Generated by Django 4.2 on 2024-08-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iziskill', '0011_video_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
