# Generated by Django 4.2 on 2024-08-30 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iziskill', '0010_course_status'),
        ('iziskill', '0012_course_slug'),
    ]

    operations = [
    ]
