# Generated by Django 5.1 on 2024-08-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iziskill', '0009_paymentrecord'),
        ('iziskill', '0013_merge_0010_course_status_0012_course_slug'),
    ]

    operations = [
    ]
